/**
 * @file gd32f4xx_mcu.h
 *
 */
/* Copyright (C) 2022-2024 by Arjan van Vught mailto:info@gd32-dmx.org
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#ifndef MCU_GD32F4XX_MCU_H_
#define MCU_GD32F4XX_MCU_H_

#if !(defined(MCU_GD32F407_MCU_H_) || defined(MCU_GD32F450_MCU_H_) || defined(MCU_GD32F470_MCU_H_))
# error This file should not be included
#endif

#include <stdint.h>

/**
 *
 */

#define BITBAND_SRAM_BASE	(uint32_t)0x22000000

/**
 * U(S)ART
 */

#define USART0_RCU_USART0		RCU_USART0
#if defined (USART0_REMAP)
# define USART0_GPIO_AFx		GPIO_AF_7
# define USART0_RCU_GPIOx		RCU_GPIOB
# define USART0_GPIOx			GPIOB
# define USART0_TX_GPIO_PINx	GPIO_PIN_6
# define USART0_RX_GPIO_PINx	GPIO_PIN_7
#else
# define USART0_GPIO_AFx		GPIO_AF_7
# define USART0_RCU_GPIOx		RCU_GPIOA
# define USART0_GPIOx			GPIOA
# define USART0_TX_GPIO_PINx	GPIO_PIN_9
# define USART0_RX_GPIO_PINx	GPIO_PIN_10
#endif

#define USART1_RCU_USART1		RCU_USART1
#if defined (USART1_REMAP)
# define USART1_GPIO_AFx		GPIO_AF_7
# define USART1_RCU_GPIOx		RCU_GPIOD
# define USART1_GPIOx			GPIOD
# define USART1_TX_GPIO_PINx	GPIO_PIN_5
# define USART1_RX_GPIO_PINx	GPIO_PIN_6
#else
# define USART1_GPIO_AFx		GPIO_AF_7
# define USART1_RCU_GPIOx		RCU_GPIOA
# define USART1_GPIOx			GPIOA
# define USART1_TX_GPIO_PINx	GPIO_PIN_2
# define USART1_RX_GPIO_PINx	GPIO_PIN_3
#endif

#define USART2_RCU_USART2		RCU_USART2
#if defined (USART2_FULL_REMAP)
# define USART2_GPIO_AFx		GPIO_AF_7
# define USART2_RCU_GPIOx		RCU_GPIOD
# define USART2_GPIOx			GPIOD
# define USART2_TX_GPIO_PINx	GPIO_PIN_8
# define USART2_RX_GPIO_PINx	GPIO_PIN_9
#elif defined (USART2_PARTIAL_REMAP)
# define USART2_GPIO_AFx		GPIO_AF_7
# define USART2_RCU_GPIOx		RCU_GPIOC
# define USART2_GPIOx			GPIOC
# define USART2_TX_GPIO_PINx	GPIO_PIN_10
# define USART2_RX_GPIO_PINx	GPIO_PIN_11
#else
# define USART2_GPIO_AFx		GPIO_AF_7
# define USART2_RCU_GPIOx		RCU_GPIOB
# define USART2_GPIOx			GPIOB
# define USART2_TX_GPIO_PINx	GPIO_PIN_10
# define USART2_RX_GPIO_PINx	GPIO_PIN_11
#endif

#define UART3_RCU_UART3			RCU_UART3
#if defined (UART3_REMAP)
# define UART3_GPIO_AFx			GPIO_AF_8
# define UART3_RCU_GPIOx		RCU_GPIOA
# define UART3_GPIOx			GPIOA
# define UART3_TX_GPIO_PINx		GPIO_PIN_0
# define UART3_RX_GPIO_PINx		GPIO_PIN_1
#else
# define UART3_GPIO_AFx			GPIO_AF_8
# define UART3_RCU_GPIOx		RCU_GPIOC
# define UART3_GPIOx			GPIOC
# define UART3_TX_GPIO_PINx		GPIO_PIN_10
# define UART3_RX_GPIO_PINx		GPIO_PIN_11
#endif

#define UART4_RCU_UART4			RCU_UART4
#define UART4_GPIO_AFx			GPIO_AF_8
#define UART4_TX_RCU_GPIOx		RCU_GPIOC
#define UART4_TX_GPIOx			GPIOC
#define UART4_TX_GPIO_PINx		GPIO_PIN_12
#define UART4_RX_RCU_GPIOx		RCU_GPIOD
#define UART4_RX_GPIOx			GPIOD
#define UART4_RX_GPIO_PINx		GPIO_PIN_2

#define USART5_RCU_USART5		RCU_USART5
#if defined (USART5_REMAP)
# define USART5_GPIO_AFx		GPIO_AF_8
# define USART5_RCU_GPIOx		RCU_GPIOG
# define USART5_GPIOx			GPIOG
# define USART5_TX_GPIO_PINx	GPIO_PIN_14
# define USART5_RX_GPIO_PINx	GPIO_PIN_9
#else
# define USART5_GPIO_AFx		GPIO_AF_8
# define USART5_RCU_GPIOx		RCU_GPIOC
# define USART5_GPIOx			GPIOC
# define USART5_TX_GPIO_PINx	GPIO_PIN_6
# define USART5_RX_GPIO_PINx	GPIO_PIN_7
#endif

#define UART6_RCU_UART6			RCU_UART6
#if defined (UART6_REMAP)
# define UART6_GPIO_AFx			GPIO_AF_8
# define UART6_RCU_GPIOx		RCU_GPIOF
# define UART6_GPIOx			GPIOF
# define UART6_TX_GPIO_PINx		GPIO_PIN_7
# define UART6_RX_GPIO_PINx		GPIO_PIN_6
#else
# define UART6_GPIO_AFx			GPIO_AF_8
# define UART6_RCU_GPIOx		RCU_GPIOE
# define UART6_GPIOx			GPIOE
# define UART6_TX_GPIO_PINx		GPIO_PIN_8
# define UART6_RX_GPIO_PINx		GPIO_PIN_7
#endif

#define UART7_RCU_UART7			RCU_UART7
#define UART7_GPIO_AFx			GPIO_AF_8
#define UART7_RCU_GPIOx			RCU_GPIOE
#define UART7_GPIOx				GPIOE
#define UART7_TX_GPIO_PINx		GPIO_PIN_1
#define UART7_RX_GPIO_PINx		GPIO_PIN_0

/**
 * I2C
 */

#define I2C0_PERIPH				I2C0
#define I2C0_RCU_I2C0			RCU_I2C0
#if defined (I2C0_REMAP)
# define I2C0_GPIO_AFx			GPIO_AF_4
# define I2C0_SCL_RCU_GPIOx		RCU_GPIOB
# define I2C0_SCL_GPIOx			GPIOB
# define I2C0_SCL_GPIO_PINx		GPIO_PIN_8
# define I2C0_SDA_RCU_GPIOx		RCU_GPIOB
# define I2C0_SDA_GPIOx			GPIOB
# define I2C0_SDA_GPIO_PINx		GPIO_PIN_9
#else
# define I2C0_GPIO_AFx			GPIO_AF_4
# define I2C0_SCL_RCU_GPIOx		RCU_GPIOB
# define I2C0_SCL_GPIOx			GPIOB
# define I2C0_SCL_GPIO_PINx		GPIO_PIN_6
# define I2C0_SDA_RCU_GPIOx		RCU_GPIOB
# define I2C0_SDA_GPIOx			GPIOB
# define I2C0_SDA_GPIO_PINx		GPIO_PIN_7
#endif

#define I2C1_PERIPH				I2C1
#define I2C1_RCU_I2C1			RCU_I2C1
#define I2C1_GPIO_AFx			GPIO_AF_4
#define I2C1_SCL_RCU_GPIOx		RCU_GPIOB
#define I2C1_SCL_GPIOx			GPIOB
#define I2C1_SCL_GPIO_PINx		GPIO_PIN_10
#define I2C1_SDA_RCU_GPIOx		RCU_GPIOB
#define I2C1_SDA_GPIOx			GPIOB
#define I2C1_SDA_GPIO_PINx		GPIO_PIN_11
//TODO I2C1 REMAP

#define I2C2_PERIPH				I2C2
#define I2C2_RCU_I2C2			RCU_I2C2
#if defined (I2C2_REMAP)
# define I2C2_GPIO_AFx			GPIO_AF_4
# define I2C2_SCL_RCU_GPIOx		RCU_GPIOH
# define I2C2_SCL_GPIOx			GPIOH
# define I2C2_SCL_GPIO_PINx		GPIO_PIN_7
# define I2C2_SDA_RCU_GPIOx		RCU_GPIOH
# define I2C2_SDA_GPIOx			GPIOH
# define I2C2_SDA_GPIO_PINx		GPIO_PIN_8
#else
# define I2C2_GPIO_AFx			GPIO_AF_4
# define I2C2_SCL_RCU_GPIOx		RCU_GPIOA
# define I2C2_SCL_GPIOx			GPIOA
# define I2C2_SCL_GPIO_PINx		GPIO_PIN_8
# define I2C2_SDA_RCU_GPIOx		RCU_GPIOC
# define I2C2_SDA_GPIOx			GPIOC
# define I2C2_SDA_GPIO_PINx		GPIO_PIN_9
#endif

/**
 * SPI
 */

#define SPI0_PERIPH				SPI0
#define SPI0_RCU_SPI0			RCU_SPI0
#if defined (SPI0_REMAP)
# define SPI0_GPIO_AFx			GPIO_AF_5
# define SPI0_GPIOx				GPIOB
# define SPI0_RCU_GPIOx			RCU_GPIOB
# define SPI0_SCK_GPIO_PINx		GPIO_PIN_3
# define SPI0_MISO_GPIO_PINx	GPIO_PIN_4
# define SPI0_MOSI_GPIO_PINx	GPIO_PIN_5
# define SPI0_NSS_RCU_GPIOx		RCU_GPIOA
# define SPI0_NSS_GPIOx			GPIOA
# define SPI0_NSS_GPIO_PINx		GPIO_PIN_15
#else
# define SPI0_GPIO_AFx			GPIO_AF_5
# define SPI0_GPIOx				GPIOA
# define SPI0_RCU_GPIOx			RCU_GPIOA
# define SPI0_SCK_GPIO_PINx		GPIO_PIN_5
# define SPI0_MISO_GPIO_PINx	GPIO_PIN_6
# define SPI0_MOSI_GPIO_PINx	GPIO_PIN_7
# define SPI0_NSS_RCU_GPIOx		RCU_GPIOA
# define SPI0_NSS_GPIOx			GPIOA
# define SPI0_NSS_GPIO_PINx		GPIO_PIN_4
#endif

#define SPI1_PERIPH				SPI1
#define SPI1_GPIO_AFx			GPIO_AF_5
#define SPI1_RCU_SPI1			RCU_SPI1
#define SPI1_RCU_GPIOx			RCU_GPIOB
#define SPI1_GPIOx				GPIOB
#define SPI1_SCK_GPIO_PINx		GPIO_PIN_13
#define SPI1_MISO_GPIO_PINx		GPIO_PIN_14
#define SPI1_MOSI_GPIO_PINx		GPIO_PIN_15
#define SPI1_NSS_RCU_GPIOx		RCU_GPIOB
#define SPI1_NSS_GPIOx			GPIOB
#define SPI1_NSS_GPIO_PINx		GPIO_PIN_12
//TODO SPI1 REMAP

#define SPI2_PERIPH				SPI2
#define SPI2_RCU_SPI2			RCU_SPI2
#if defined (SPI2_REMAP)
# define SPI2_GPIO_AFx			GPIO_AF_6
# define SPI2_RCU_GPIOx			RCU_GPIOC
# define SPI2_GPIOx				GPIOC
# define SPI2_SCK_GPIO_PINx		GPIO_PIN_10
# define SPI2_MISO_GPIO_PINx	GPIO_PIN_11
# define SPI2_MOSI_GPIO_PINx	GPIO_PIN_12
# define SPI2_NSS_RCU_GPIOx		RCU_GPIOA
# define SPI2_NSS_GPIOx			GPIOA
# define SPI2_NSS_GPIO_PINx		GPIO_PIN_4
#else
# define SPI2_GPIO_AFx			GPIO_AF_6
# define SPI2_RCU_GPIOx			RCU_GPIOB
# define SPI2_GPIOx				GPIOB
# define SPI2_SCK_GPIO_PINx		GPIO_PIN_3
# define SPI2_MISO_GPIO_PINx	GPIO_PIN_4
# define SPI2_MOSI_GPIO_PINx	GPIO_PIN_5
# define SPI2_NSS_RCU_GPIOx		RCU_GPIOA
# define SPI2_NSS_GPIOx			GPIOA
# define SPI2_NSS_GPIO_PINx		GPIO_PIN_15
#endif

#define SPI5_PERIPH				SPI5
#define SPI5_RCU_SPI5			RCU_SPI5
#define SPI5_GPIO_AFx			GPIO_AF_5
#define SPI5_RCU_GPIOx			RCU_GPIOG
#define SPI5_GPIOx				GPIOG
#define SPI5_SCK_GPIO_PINx		GPIO_PIN_13
#define SPI5_MISO_GPIO_PINx		GPIO_PIN_12
#define SPI5_MOSI_GPIO_PINx		GPIO_PIN_14
#define SPI5_IO2_GPIO_PINx		GPIO_PIN_10
#define SPI5_IO3_GPIO_PINx		GPIO_PIN_11
#define SPI5_NSS_RCU_GPIOx		RCU_GPIOG
#define SPI5_NSS_GPIOx			GPIOG
#define SPI5_NSS_GPIO_PINx		GPIO_PIN_9

/**
 * TIMER GPIO
 */

#define TIMER2CH0_RCU_GPIOx		RCU_GPIOA
#define TIMER2CH0_AFx			GPIO_AF_2
#define TIMER2CH0_GPIOx			GPIOA
#define TIMER2CH0_GPIO_PINx		GPIO_PIN_6

#if defined(TIMER2_FULL_REMAP)
# define TIMER2_GPIO_AFx		GPIO_AF_2
# define TIMER2_CH0_RCU_GPIOx	RCU_GPIOC
# define TIMER2_CH0_GPIOx		GPIOC
# define TIMER2_CH0_GPIO_PINx	GPIO_PIN_6

# define TIMER2_CH1_RCU_GPIOx	RCU_GPIOC
# define TIMER2_CH1_GPIOx		GPIOC
# define TIMER2_CH1_GPIO_PINx	GPIO_PIN_7

# define TIMER2_CH2_RCU_GPIOx	RCU_GPIOC
# define TIMER2_CH2_GPIOx		GPIOC
# define TIMER2_CH2_GPIO_PINx	GPIO_PIN_8

# define TIMER2_CH3_RCU_GPIOx	RCU_GPIOC
# define TIMER2_CH3_GPIOx		GPIOC
# define TIMER2_CH3_GPIO_PINx	GPIO_PIN_9
#elif defined(TIMER2_PARTIAL_REMAP)
# define TIMER2_GPIO_AFx		GPIO_AF_2
# define TIMER2_CH0_RCU_GPIOx	RCU_GPIOB
# define TIMER2_CH0_GPIOx		GPIOB
# define TIMER2_CH0_GPIO_PINx	GPIO_PIN_4

# define TIMER2_CH1_RCU_GPIOx	RCU_GPIOB
# define TIMER2_CH1_GPIOx		GPIOB
# define TIMER2_CH1_GPIO_PINx	GPIO_PIN_5

# define TIMER2_CH2_RCU_GPIOx	RCU_GPIOB
# define TIMER2_CH2_GPIOx		GPIOB
# define TIMER2_CH2_GPIO_PINx	GPIO_PIN_0

# define TIMER2_CH3_RCU_GPIOx	RCU_GPIOB
# define TIMER2_CH3_GPIOx		GPIOB
# define TIMER2_CH3_GPIO_PINx	GPIO_PIN_1
#else
# define TIMER2_GPIO_AFx		GPIO_AF_2
# define TIMER2_CH0_RCU_GPIOx	RCU_GPIOA
# define TIMER2_CH0_GPIOx		GPIOA
# define TIMER2_CH0_GPIO_PINx	GPIO_PIN_6

# define TIMER2_CH1_RCU_GPIOx	RCU_GPIOA
# define TIMER2_CH1_GPIOx		GPIOA
# define TIMER2_CH1_GPIO_PINx	GPIO_PIN_7

# define TIMER2_CH2_RCU_GPIOx	RCU_GPIOB
# define TIMER2_CH2_GPIOx		GPIOB
# define TIMER2_CH2_GPIO_PINx	GPIO_PIN_0

# define TIMER2_CH3_RCU_GPIOx	RCU_GPIOB
# define TIMER2_CH3_GPIOx		GPIOB
# define TIMER2_CH3_GPIO_PINx	GPIO_PIN_1
#endif

/**
 * DMA
 */

#define SPI0_DMAx				DMA1
#define SPI0_TX_DMA_CHx			DMA_CH2
#define SPI0_TX_DMA_SUBPERIx    DMA_SUBPERI3

#define SPI1_DMAx				DMA0
#define SPI1_TX_DMA_CHx			DMA_CH4
#define SPI1_TX_DMA_SUBPERIx    DMA_SUBPERI0

#define SPI2_DMAx				DMA0
#define SPI2_TX_DMA_CHx			DMA_CH5
#define SPI2_TX_DMA_SUBPERIx	DMA_SUBPERI0

#define SPI3_DMAx               DMA1
#define SPI3_TX_DMA_CHx         DMA_CH1
#define SPI3_TX_DMA_SUBPERIx    DMA_SUBPER4

#define SPI4_DMAx               DMA1
#define SPI4_TX_DMA_CHx         DMA_CH4
#define SPI4_TX_DMA_SUBPERIx    DMA_SUBPERI2

#define SPI5_DMAx               DMA1
#define SPI5_TX_DMA_CHx         DMA_CH5
#define SPI5_TX_DMA_SUBPERIx    DMA_SUBPERI1

#define TIMER2_RCU_DMAx         RCU_DMA0
#define TIMER2_DMAx             DMA0
#define TIMER2_CH0_DMA_CHx      DMA_CH4
#define TIMER2_CH0_DMA_SUBPERIx DMA_SUBPERI5
#define TIMER2_CH1_DMA_CHx      DMA_CH5
#define TIMER2_CH1_DMA_SUBPERIx DMA_SUBPERI5
#define TIMER2_CH2_DMA_CHx      DMA_CH7
#define TIMER2_CH2_DMA_SUBPERIx DMA_SUBPERI5
#define TIMER2_CH3_DMA_CHx      DMA_CH2
#define TIMER2_CH3_DMA_SUBPERIx DMA_SUBPERI5

#define TIMER7_RCU_DMAx         RCU_DMA1
#define TIMER7_DMAx             DMA1
#define TIMER7_CH0_DMA_CHx      DMA_CH2
#define TIMER7_CH0_DMA_SUBPERIx DMA_SUBPERI7
#define TIMER7_CH1_DMA_CHx      DMA_CH3
#define TIMER7_CH1_DMA_SUBPERIx DMA_SUBPERI7
#define TIMER7_CH2_DMA_CHx      DMA_CH4
#define TIMER7_CH2_DMA_SUBPERIx DMA_SUBPERI7

#define USART0_DMAx				DMA1
#define USART0_TX_DMA_CHx		DMA_CH7
#define USART0_TX_DMA_SUBPERIx  DMA_SUBPERI4
#define USART0_RX_DMA_CHx		DMA_CH5
#define USART0_RX_DMA_SUBPERIx  DMA_SUBPERI4

#define USART1_DMAx				DMA0
#define USART1_TX_DMA_CHx		DMA_CH6
#define USART1_TX_DMA_SUBPERIx	DMA_SUBPERI4
#define USART1_RX_DMA_CHx		DMA_CH5
#define USART1_RX_DMA_SUBPERIx	DMA_SUBPERI4

#define USART2_DMAx				DMA0
#define USART2_TX_DMA_CHx		DMA_CH3
#define USART2_TX_DMA_SUBPERIx	DMA_SUBPERI4
#define USART2_RX_DMA_CHx		DMA_CH1
#define USART2_RX_DMA_SUBPERIx	DMA_SUBPERI4

#define UART3_DMAx				DMA0
#define UART3_TX_DMA_CHx		DMA_CH4
#define UART3_TX_DMA_SUBPERIx   DMA_SUBPERI4
#define UART3_RX_DMA_CHx		DMA_CH2
#define UART3_RX_DMA_SUBPERIx   DMA_SUBPERI4

#define UART4_DMAx				DMA0
#define UART4_TX_DMA_CHx		DMA_CH7
#define UART4_TX_DMA_SUBPERIx   DMA_SUBPERI4
#define UART4_RX_DMA_CHx		DMA_CH0
#define UART4_RX_DMA_SUBPERIx   DMA_SUBPERI4

#define USART5_DMAx				DMA1
#define USART5_TX_DMA_CHx		DMA_CH6
#define USART5_TX_DMA_SUBPERIx  DMA_SUBPERI5
#define USART5_RX_DMA_CHx		DMA_CH1
#define USART5_RX_DMA_SUBPERIx  DMA_SUBPERI5

#define UART6_DMAx				DMA0
#define UART6_TX_DMA_CHx		DMA_CH1
#define UART6_TX_DMA_SUBPERIx   DMA_SUBPERI5
#define UART6_RX_DMA_CHx		DMA_CH3
#define UART6_RX_DMA_SUBPERIx   DMA_SUBPERI5

#define UART7_DMAx				DMA0
#define UART7_TX_DMA_CHx		DMA_CH0
#define UART7_TX_DMA_SUBPERIx   DMA_SUBPERI5
#define UART7_RX_DMA_CHx		DMA_CH6
#define UART7_RX_DMA_SUBPERIx   DMA_SUBPERI5

#endif /* MCU_GD32F4XX_MCU_H_ */
