DEFINES=NDEBUG

EXTRA_INCLUDES=

EXTRA_SRCDIR=

ifneq ($(MAKE_FLAGS),)
	ifeq ($(findstring CONFIG_NET_ENABLE_PTP,$(MAKE_FLAGS)), CONFIG_NET_ENABLE_PTP)	
  	EXTRA_SRCDIR+=src/gd32/time_ptp
  else
  	ifeq ($(findstring CONFIG_TIME_USE_TIMER,$(MAKE_FLAGS)), CONFIG_TIME_USE_TIMER)
  		EXTRA_SRCDIR+=src/gd32/time_timer
  	else
  		ifeq ($(findstring CONFIG_TIME_USE_SYSTICK,$(MAKE_FLAGS)), CONFIG_TIME_USE_SYSTICK)
  			EXTRA_SRCDIR+=src/gd32/time_systick
  		endif
  	endif
  endif
else
	EXTRA_SRCDIR+=src/gd32/time_timer
	DEFINES+=CONFIG_TIME_USE_TIMER
endif
  
include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk