DEFINES=DISABLE_FS NDEBUG
EXTRA_INCLUDES=../lib-artnet/include ../lib-e131/include ../lib-properties/include ../lib-spiflashstore/include ../lib-lightset/include ../lib-network/include

include ../firmware-template-gd32/lib/Rules.mk
