DEFINES=#NDEBUG

EXTRA_INCLUDES=../lib-dmx/include ../lib-rdm/include ../lib-artnet/include ../lib-lightset/include ../lib-hal/include

include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk
