DEFINES =DISABLE_FS 
DEFINES+=NDEBUG

EXTRA_INCLUDES=../lib-dmxnode/include

ifeq ($(findstring ARTNET_HAVE_FAILSAFE_RECORD,$(MAKE_FLAGS)), ARTNET_HAVE_FAILSAFE_RECORD)
	EXTRA_SRCDIR+=src/node/failsafe/spi
	EXTRA_INCLUDES+=src/node/failsafe
endif

include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk