DEFINES=NODE_RDMNET_LLRP_ONLY 
DEFINES+=NDEBUG


EXTRA_INCLUDES=../lib-rdm/include ../lib-rdmsensor/include ../lib-rdmsubdevice/include ../lib-e131/include ../lib-network/include ../lib-lightset/include

include ../firmware-template-gd32/lib/Rules.mk
