DEFINES=USE_SPI_DMA
#DEFINES+=NDEBUG

EXTRA_INCLUDES=../lib-ws28xx/include ../lib-lightset/include ../lib-properties/include

EXTRA_SRCDIR=

include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk
