DEFINES+=DISABLE_RTC
DEFINES+=DISABLE_FS
DEFINES+=DISABLE_PRINTF_FLOAT

DEFINES+=ENABLE_TFTP_SERVER
DEFINES+=CONFIG_REMOTECONFIG_MINIMUM

DEFINES+=CONFIG_NETWORK_MEMORY_BLOCKS=1 

DEFINES+=UDP_MAX_PORTS_ALLOWED=3
DEFINES+=ENET_RXBUF_NUM=2 ENET_TXBUF_NUM=2

SRCDIR=firmware lib

LIBS=remoteconfig flashcodeinstall configstore display flashcode flash
