DEFINES+=NODE_ARTNET_MULTI ARTNET_VERSION=4
DEFINES+=ARTNET_HAVE_DMXIN
DEFINES+=ARTNET_HAVE_FAILSAFE_RECORD

DEFINES+=OUTPUT_DMX_SEND_MULTI
DEFINES+=OUTPUT_HAVE_STYLESWITCH

DEFINES+=RDM_CONTROLLER

DEFINES+=CONFIG_STORE_USE_SPI

DEFINES+=RTL8201F_LED1_LINK_ALL

DEFINES+=DISPLAY_UDF 

DEFINES+=ENABLE_HTTPD ENABLE_CONTENT

DEFINES+=DISABLE_RTC
DEFINES+=DISABLE_FS