BOARD=BOARD_GD32F407RE

DEFINES=LIGHTSET_PORTS=2

DEFINES+=ENET_RXBUF_NUM=8 ENET_TXBUF_NUM=4

#

#

DEFINES+=DEBUG_STACK
DEFINES+=NDEBUG

LIBS=

SRCDIR=firmware lib

include Common.mk
include ../firmware-template-gd32/Rules.mk

prerequisites:
